Remove mocket
maxmind/GeoIP2-python pull request #173
Opened 2024-07-04 20:22 UTC by shadromani

2024-07-08 17:11 UTC, oschwald requested changes
Nice! I had a few comments.

2024-07-08 17:11 UTC, oschwald commented on tests/webservice_test.py
> +            return ""
The custom handler is a bit confusing. I think we could eliminate it by using `headers` or `header_value_matcher` to match the expected headers on `expect_request`. I don't think we need to test the path again.

2024-07-08 17:11 UTC, oschwald commented on tests/webservice_test.py
> +            "/geoip/v2.1/insights/" + "1.2.3.4"
```suggestion
            "/geoip/v2.1/insights/1.2.3.4"
```

2024-07-08 17:11 UTC, oschwald commented on tests/webservice_test.py
> +            content_type=self._content_type("insights"),
:+1:

2024-07-08 17:11 UTC, oschwald commented on tests/webservice_test.py
> +        self.client._base_uri = self.httpserver.url_for("/") + "geoip/v2.1"
```suggestion
        self.client._base_uri = self.httpserver.url_for("/geoip/v2.1")
```

And below.

2024-07-08 19:01 UTC, shadromani commented on tests/webservice_test.py
> +        self.httpserver.expect_request("/geoip/v2.1/country/1.2.3.4").respond_with_json(
Will you please elaborate how? The test has different responses depending on the specific ip and we can not return the default on all requests.

2024-07-08 20:23 UTC, shadromani commented on tests/webservice_test.py
> +        self.httpserver.expect_request("/geoip/v2.1/country/1.2.3.4").respond_with_json(
I see, I misread your comment.

2024-07-09 19:04 UTC, oschwald requested changes

2024-07-09 19:04 UTC, oschwald commented on tests/webservice_test.py
> +            "User-Agent": lambda x: x.startswith("GeoIP2-Python-Client/"),})
I don't think this is the correct usage of `HeaderValueMatcher`. I think you still set `headers`, but you would want to define a custom matcher for "User-Agent".

[See the docs](https://pytest-httpserver.readthedocs.io/en/latest/howto.html#advanced-header-matching).

2024-07-11 17:20 UTC, oschwald requested changes

2024-07-11 17:20 UTC, oschwald commented on tests/webservice_test.py
> +            ),
I don't think this works either. If I change the values, the tests don't fail. I was expecting something like this:

```
        def user_agent_compare(actual: str, expected: str) -> bool:
            if actual is None:
                return False
            return actual.startswith(expected)

        self.httpserver.expect_request(
            "/geoip/v2.1/country/1.2.3.4",
            method="GET",
            headers={
                    "Accept": "application/json",
                    "Authorization": "Basic NDI6YWJjZGVmMTIzNDU2",
                    "User-Agent": "GeoIP2-Python-Client/"
            },
            header_value_matcher=HeaderValueMatcher(defaultdict(
                lambda: HeaderValueMatcher.default_header_value_matcher,
                {"User-Agent": user_agent_compare}
            )),
        ).respond_with_json(
            self.country,
            status=200,
            content_type=self._content_type("country"),
        )
```

Alternatively, you could modify the default matcher as directed in the docs.

2024-07-16 14:38 UTC, oschwald approved these changes

2024-07-16 14:38 UTC, merged

2024-07-29 14:48 UTC, deronnax commented
I'm curious, what's the rational behind the switch from mocket to http-server?

2024-07-29 16:46 UTC, oschwald commented
We unfortunately had quite a few problem with it breaking, e.g., on new or old Python versions, on new `aiohttp` versions, on particular OSes, etc. If you search the pull requests for "mocket", you will see a subset of those.

We decided to use `pytest-httpserver` as it implements an actual HTTP server, which should be less prone to these sorts of issues.